version: '3.7'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - STAGE=""
    env_file:
      - .env
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - backend
  db:
    image: postgres:14.2-alpine3.15
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis:7.0.7
    ports:
      - "6379:6379"
